# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 00:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0003_auto_20170929_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alliance',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('ticker', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('ticker', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='alliance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eveauth.Alliance'),
        ),
        migrations.AddField(
            model_name='profile',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eveauth.Character'),
        ),
        migrations.AddField(
            model_name='profile',
            name='corporation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eveauth.Corporation'),
        ),
    ]
