# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0008_templink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templink',
            name='expires',
            field=models.DateTimeField(null=True),
        ),
    ]
