# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0009_auto_20171001_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='templink',
            name='link',
            field=models.CharField(db_index=True, default=b'', max_length=12),
        ),
        migrations.AlterField(
            model_name='templink',
            name='expires',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
