# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0010_auto_20171001_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='templink',
            name='created',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
