# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0011_templink_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='templink',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
