# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0012_templink_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templink',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
