# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0013_auto_20171001_0025'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplinkUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now=True)),
                ('templink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='eveauth.Templink')),
            ],
        ),
    ]
