# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0014_templinkuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templinkuser',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
