# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0015_auto_20171001_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='templinkuser',
            name='password',
            field=models.CharField(default='asd', max_length=32),
            preserve_default=False,
        ),
    ]
