# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0016_templinkuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templinkuser',
            name='password',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
