# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0017_auto_20171001_0252'),
    ]

    operations = [
        migrations.CreateModel(
            name='MurmurChannel',
            fields=[
                ('channel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('inheritacl', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'murmur_channels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MurmurServer',
            fields=[
                ('server_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'murmur_servers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MurmurUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('pw', models.CharField(max_length=128)),
                ('texture', models.BinaryField()),
                ('last_active', django_unixdatetimefield.fields.UnixDateTimeField()),
            ],
            options={
                'db_table': 'murmur_users',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='templinkuser',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='templinkuser',
            unique_together=set([('templink', 'name')]),
        ),
    ]
