# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0019_auto_20171003_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='forum_password',
        ),
        migrations.AddField(
            model_name='profile',
            name='forum_id',
            field=models.IntegerField(null=True),
        ),
    ]
