# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 22:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('eveauth', '0020_auto_20171006_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open', models.BooleanField(default=False)),
                ('apply', models.BooleanField(default=False)),
                ('is_mumble', models.BooleanField(default=True)),
                ('is_forum', models.BooleanField(default=False)),
                ('is_discord', models.BooleanField(default=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='auth.Group')),
            ],
        ),
    ]
