# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 22:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0022_auto_20171015_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupdetails',
            old_name='apply',
            new_name='can_apply',
        ),
        migrations.RenameField(
            model_name='groupdetails',
            old_name='open',
            new_name='is_open',
        ),
    ]
