# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 23:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eveauth', '0024_groupapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupapp',
            name='accepted',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='groupapp',
            name='completed',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='groupapp',
            name='completed_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
