# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0007_auto_20171222_2155'),
        ('eveauth', '0026_auto_20171227_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='alliance',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eveauth.Alliance'),
        ),
        migrations.AddField(
            model_name='character',
            name='corp',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eveauth.Corporation'),
        ),
        migrations.AddField(
            model_name='character',
            name='ship',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sde.Type'),
        ),
        migrations.AddField(
            model_name='character',
            name='system',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sde.System'),
        ),
        migrations.AddField(
            model_name='character',
            name='wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
