# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 12:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0027_auto_20171227_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
    ]
