# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 02:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0029_auto_20171228_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name']},
        ),
    ]
