# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0009_auto_20171228_1243'),
        ('eveauth', '0030_auto_20171229_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0)),
                ('raw_quantity', models.IntegerField(default=0)),
                ('singleton', models.BooleanField()),
                ('name', models.CharField(default=None, max_length=64, null=True)),
                ('parent', models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='eveauth.Asset')),
                ('station', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sde.Station')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sde.System')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sde.Type')),
            ],
        ),
    ]
