# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0009_auto_20171228_1243'),
        ('eveauth', '0031_asset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trained_skill_level', models.IntegerField()),
                ('active_skill_level', models.IntegerField()),
                ('skillpoints_in_skill', models.IntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sde.Type')),
            ],
        ),
    ]
