# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0032_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='character',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eveauth.Character'),
            preserve_default=False,
        ),
    ]
