# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0033_skill_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='flag',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
