# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0035_asset_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='system',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sde.System'),
        ),
    ]
