# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0036_auto_20171229_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='eveauth.Character'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='eveauth.Character'),
        ),
    ]
