# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0037_auto_20171229_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='parent',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='eveauth.Asset'),
        ),
    ]
