# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0038_auto_20171230_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='flag',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
