# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0019_auto_20171231_0418'),
        ('eveauth', '0042_auto_20180105_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Implant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implants', to='eveauth.Character')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sde.Type')),
            ],
        ),
    ]
