# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-06 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0019_auto_20171231_0418'),
        ('eveauth', '0043_implant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clone',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=b'', max_length=100)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clones', to='eveauth.Character')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jump_clones', to='sde.Station')),
            ],
        ),
        migrations.CreateModel(
            name='CloneImplant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implants', to='eveauth.Clone')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sde.Type')),
            ],
        ),
        migrations.AlterField(
            model_name='implant',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implants', to='sde.Type'),
        ),
    ]
