# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-09 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0046_auto_20180119_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='eveauth.Character')),
            ],
        ),
    ]
