# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-09 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0047_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='corporation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='eveauth.Corporation'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='character',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='eveauth.Character'),
        ),
    ]
