# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-11 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0023_auto_20180309_0240'),
        ('eveauth', '0048_auto_20180309_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('profile_id', models.IntegerField()),
                ('state', models.CharField(max_length=64)),
                ('reinforce_weekday', models.IntegerField(choices=[(0, b'Monday'), (1, b'Tuesday'), (2, b'Wednesday'), (3, b'Thursday'), (4, b'Friday'), (5, b'Saturday'), (6, b'Sunday')])),
                ('reinforce_hour', models.IntegerField()),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='eveauth.Corporation')),
                ('station', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corp_structure', to='sde.Station')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='sde.System')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structures', to='sde.Type')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='eveauth.Structure'),
        ),
    ]
