# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-15 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0054_structure_fuel_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField(default=b'')),
                ('sender_id', models.IntegerField(default=None, null=True)),
                ('sender_type', models.CharField(db_index=True, max_length=64)),
                ('date', models.DateTimeField(default=None, null=True)),
                ('type', models.CharField(db_index=True, max_length=64)),
            ],
        ),
    ]
