# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-29 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0059_auto_20180323_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='member_visible_until',
            field=models.DateTimeField(db_index=True, default=None, null=True),
        ),
    ]
