# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-29 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0060_character_member_visible_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='member_visible_until',
        ),
        migrations.AddField(
            model_name='character',
            name='visible_to',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='visible_until',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
