# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-05 20:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0061_auto_20180329_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='alliance',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='eveauth.Alliance'),
        ),
        migrations.AlterField(
            model_name='character',
            name='corp',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='eveauth.Corporation'),
        ),
        migrations.AlterField(
            model_name='character',
            name='home',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to='sde.Station'),
        ),
        migrations.AlterField(
            model_name='character',
            name='owner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='character',
            name='ship',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sde.Type'),
        ),
        migrations.AlterField(
            model_name='character',
            name='system',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sde.System'),
        ),
        migrations.AlterField(
            model_name='character',
            name='token',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='social_django.UserSocialAuth'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='alliance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveauth.Alliance'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveauth.Character'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='corporation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eveauth.Corporation'),
        ),
    ]
