# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-09 12:39
from __future__ import unicode_literals

from django.db import migrations


def add_groups(apps, schema_editor):
    from django.contrib.auth.models import Group

    logistics, logistics_created = Group.objects.get_or_create(name="Logistics")
    audit, audit_created = Group.objects.get_or_create(name="Audit")

    if logistics_created:
        logistics.details.is_open = False
        logistics.details.can_apply = True
        logistics.details.forum = True
        logistics.details.discord = True
        logistics.details.save()

    if audit_created:
        audit.details.is_open = False
        audit.details.can_apply = True
        audit.details.forum = True
        audit.details.discord = True
        audit.details.save()

    admin, admin_created = Group.objects.get_or_create(name="admin")
    fc, fc_created = Group.objects.get_or_create(name="FC")

    if admin_created:
        admin.details.is_open = True
        admin.details.forum = True
        admin.details.discord = True
        admin.details.save()

    if fc_created:
        fc.details.can_apply = True
        fc.details.forum = True
        fc.details.discord = True
        fc.details.save()


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0062_auto_20180505_2035'),
    ]

    operations = [
	migrations.RunPython(add_groups),
    ]
