# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-31 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0024_auto_20180530_1819'),
        ('eveauth', '0064_auto_20180804_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTraining',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_sp', models.IntegerField(default=0)),
                ('end_sp', models.IntegerField(default=0)),
                ('training_to_level', models.IntegerField(default=0)),
                ('position', models.IntegerField(db_index=True, default=0)),
                ('starts', models.DateTimeField(db_index=True, default=None, null=True)),
                ('ends', models.DateTimeField(db_index=True, default=None, null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_skills', to='eveauth.Character')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sde.Type')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
