# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-02 10:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0024_auto_20180530_1819'),
        ('eveauth', '0065_skilltraining'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequirementSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('recommended_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='eveauth.Requirement')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirement_skills', to='sde.Type')),
            ],
        ),
    ]
