# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-02 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0066_requirement_requirementskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
