# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-21 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveauth', '0069_auto_20181114_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupapp',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='groupapp',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
