# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-15 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('timerboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='visible_to_groups',
            field=models.ManyToManyField(blank=True, related_name='timers', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='timer',
            name='visible_to_level',
            field=models.IntegerField(choices=[(0, 'Non-Members'), (1, 'Blues'), (2, 'Members')], default=2),
        ),
    ]
