# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-15 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timerboard', '0002_auto_20180215_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='timer',
            name='owner',
            field=models.CharField(default='AVRSE', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timer',
            name='side',
            field=models.IntegerField(choices=[(0, 'Friendly'), (1, 'Hostile'), (2, 'Third-Party')], default=1),
        ),
    ]
