# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-15 15:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timerboard', '0004_timer_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='deleted_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_timers', to=settings.AUTH_USER_MODEL),
        ),
    ]
