# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-15 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timerboard', '0005_timer_deleted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='stage',
            field=models.CharField(choices=[('AN', 'Anchoring'), ('AR', 'Armor'), ('ST', 'Structure')], db_index=True, max_length=2),
        ),
    ]
