# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-09 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timerboard', '0006_auto_20180215_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='stage',
            field=models.CharField(choices=[('AN', 'Anchoring'), ('AR', 'Armor'), ('ST', 'Structure'), ('UN', 'Unanchoring')], db_index=True, max_length=2),
        ),
    ]
