# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('icon_id', models.IntegerField(null=True)),
                ('published', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Constellation',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('radius', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('icon_id', models.IntegerField(null=True)),
                ('anchored', models.BooleanField()),
                ('anchorable', models.BooleanField()),
                ('fittableNonSingleton', models.BooleanField()),
                ('published', models.BooleanField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sde.Category')),
            ],
        ),
        migrations.CreateModel(
            name='MarketGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_id', models.IntegerField(null=True)),
                ('hasTypes', models.BooleanField()),
                ('parent', models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sde.MarketGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('radius', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('luminosity', models.FloatField()),
                ('border', models.BooleanField()),
                ('fringe', models.BooleanField()),
                ('corridor', models.BooleanField()),
                ('hub', models.BooleanField()),
                ('international', models.BooleanField()),
                ('security', models.FloatField()),
                ('radius', models.FloatField()),
                ('security_class', models.CharField(max_length=2)),
                ('constellation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='sde.Constellation')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='sde.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('mass', models.FloatField(null=True)),
                ('volume', models.FloatField(null=True)),
                ('capacity', models.FloatField(null=True)),
                ('published', models.BooleanField()),
                ('icon_id', models.IntegerField(null=True)),
                ('market_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sde.MarketGroup')),
            ],
        ),
        migrations.AddField(
            model_name='system',
            name='sun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sde.Type'),
        ),
        migrations.AddField(
            model_name='constellation',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constellations', to='sde.Region'),
        ),
    ]
