# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketgroup',
            old_name='hasTypes',
            new_name='has_types',
        ),
    ]
