# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0003_auto_20171222_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constellation',
            name='radius',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='radius',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='radius',
            field=models.FloatField(null=True),
        ),
    ]
