# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0004_auto_20171222_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketgroup',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
