# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-22 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0005_auto_20171222_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='market_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sde.MarketGroup'),
        ),
    ]
