# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0007_auto_20171222_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('structure', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sde.System')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sde.Type')),
            ],
        ),
    ]
