# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-28 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0008_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='structure',
            field=models.BooleanField(default=False),
        ),
    ]
