# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0009_auto_20171228_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sde.Group'),
        ),
    ]
