# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0010_type_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='system',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sde.System'),
        ),
        migrations.AlterField(
            model_name='station',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sde.Type'),
        ),
        migrations.AlterField(
            model_name='station',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='station',
            name='y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='station',
            name='z',
            field=models.FloatField(default=0),
        ),
    ]
