# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0012_attributecategory_attributetype_typeattribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attributetype',
            old_name='iconID',
            new_name='icon_id',
        ),
        migrations.RenameField(
            model_name='attributetype',
            old_name='unitID',
            new_name='unit_id',
        ),
        migrations.AddField(
            model_name='typeattribute',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='sde.Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attributetype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='sde.AttributeCategory'),
        ),
        migrations.AlterField(
            model_name='typeattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='sde.AttributeType'),
        ),
        migrations.AlterField(
            model_name='typeattribute',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
