# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0013_auto_20171230_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributetype',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='sde.AttributeCategory'),
        ),
    ]
