# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0014_auto_20171230_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributecategory',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attributecategory',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
