# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0015_auto_20171230_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributetype',
            name='category',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='types', to='sde.AttributeCategory'),
        ),
    ]
