# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0016_auto_20171230_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeattribute',
            name='value',
        ),
        migrations.AddField(
            model_name='typeattribute',
            name='value_float',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='typeattribute',
            name='value_int',
            field=models.IntegerField(null=True),
        ),
    ]
