# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0017_auto_20171230_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='buy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='type',
            name='sell',
            field=models.FloatField(default=0),
        ),
    ]
