# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0018_auto_20171231_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='buy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='type',
            name='sell',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
