# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-15 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0019_auto_20171231_0418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['name']},
        ),
    ]
