# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-15 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0020_auto_20180215_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ['name']},
        ),
    ]
