# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-30 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sde', '0023_auto_20180309_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='sun',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='sde.Type'),
        ),
    ]
