# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-14 18:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlarumGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[(b'access_level', b'Access Level'), (b'corp', b'Corp'), (b'alliance', b'Alliance'), (b'group', b'Group')], db_index=True, max_length=32)),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='FlarumUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flarum', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
