# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-16 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flarum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flarumgroup',
            old_name='name',
            new_name='name_singular',
        ),
        migrations.AddField(
            model_name='flarumgroup',
            name='name_plural',
            field=models.CharField(db_index=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flarumuser',
            name='email',
            field=models.CharField(db_index=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flarumuser',
            name='last_seen_time',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='flarumuser',
            name='username',
            field=models.CharField(db_index=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flarumuser',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flarum', to=settings.AUTH_USER_MODEL),
        ),
    ]
