# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-16 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flarum', '0002_auto_20181116_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='flarumuser',
            name='groups',
            field=models.ManyToManyField(related_name='users', to='flarum.FlarumGroup'),
        ),
    ]
