# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-16 17:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flarum', '0003_flarumuser_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='flarumgroup',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 11, 16, 17, 51, 36, 609376, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flarumgroup',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='flarumuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 11, 16, 17, 51, 40, 246663, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flarumuser',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='flarumgroup',
            name='type',
            field=models.CharField(choices=[(b'access_level', b'Access Level'), (b'corp', b'Corp'), (b'alliance', b'Alliance'), (b'group', b'Group'), (b'forum_group', b'Forum Group')], db_index=True, max_length=32),
        ),
    ]
