# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-13 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_auto_20180313_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='event',
            field=models.CharField(choices=[(b'structure_reinforce', b'Structure Reinforce'), (b'low_fuel', b'Low Fuel')], db_index=True, max_length=64),
        ),
    ]
