# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-13 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20180313_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhook',
            name='notify',
            field=models.CharField(choices=[(b'', b''), (b'@here', b'@here'), (b'@everyone', b'@everyone')], default=b'', max_length=32),
        ),
    ]
