# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-14 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_webhook_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='event',
            field=models.CharField(choices=[(b'structure_reinforce', b'Structure Reinforce'), (b'structure_anchoring', b'Structure Anchor/Unanchor'), (b'low_fuel', b'Low Fuel')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='notify',
            field=models.CharField(choices=[(b'', b'No'), (b'@here', b'@here'), (b'@everyone', b'@everyone')], default=b'', max_length=32),
        ),
    ]
