# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-23 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0008_auto_20180316_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='event',
            field=models.CharField(choices=[(b'structure_reinforce', b'Structure Reinforce'), (b'structure_anchoring', b'Structure Anchor/Unanchor'), (b'low_fuel_filtered', b'Low Fuel (Filtered)'), (b'low_fuel_all', b'Low Fuel (All)'), (b'structure_attacked', b'Structured Attacked'), (b'group_app', b'New Group Application')], db_index=True, max_length=64),
        ),
    ]
