# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-29 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0009_auto_20180323_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhook',
            name='active',
            field=models.BooleanField(default=True, verbose_name=b'Active'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='event',
            field=models.CharField(choices=[(b'structure_reinforce', b'Structure Reinforce'), (b'structure_anchoring', b'Structure Anchor/Unanchor'), (b'low_fuel_filtered', b'Low Fuel (Filtered)'), (b'low_fuel_all', b'Low Fuel (All)'), (b'structure_attacked', b'Structured Attacked'), (b'group_app', b'New Group Application')], db_index=True, max_length=64, verbose_name=b'Event'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='notify',
            field=models.CharField(blank=True, choices=[(b'', b'No'), (b'@here', b'@here'), (b'@everyone', b'@everyone')], default=b'', max_length=32, verbose_name=b'Notify'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='url',
            field=models.CharField(max_length=512, verbose_name=b'URL'),
        ),
    ]
